Updates
UdL-EPS-SoftArch/LearnIT-API pull request #14
Opened 2020-03-24 17:54 UTC by juanudl96

2020-03-24 17:55 UTC, juanudl96 commented
For pulling new commints

2020-03-24 19:03 UTC, bergacat1 requested changes

2020-03-24 19:03 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/learnphysics/repository/ExamRepository.java
> +public interface ExamRepository {
You should add the annotations and extend the corresponding class in order that this class exposes the http endpoints. It is not doing anything right now.

2020-03-25 17:55 UTC, bergacat1 approved these changes

2020-03-25 18:29 UTC, bergacat1 submitted a review, later dismissed

2020-03-25 18:29 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/learnphysics/domain/Question.java
>  public class Question {
Without the annotation @Entity Spring does not know this is a class of the model and you can not create relations with other classes. This is causing the application to crash.

2020-03-25 18:30 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/learnphysics/domain/Question.java
>  public class Question {
Check that the annotation is present in all classes of the model.

2020-03-29 12:33 UTC, rogargon approved these changes

2020-03-29 12:34 UTC, merged